spring.application.name=${SPRING_APPLICATION_NAME:agrosensor-backend}
server.port=${SERVER_PORT}


# --- Database ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:false}

# --- JWT ---
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}
application.security.jwt.refresh-token.expiration=${APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# --- Mail ---
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}



